name: Build AtmoLin für Windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          install-deps: 'true'
          setup-python: 'true'
      
      - uses: ilammy/msvc-dev-cmd@v1

      - name: Run qmake and nmake
        shell: cmd
        run: |
          cmake .
          nmake
